name: Documentation

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-deploy:
    uses: TeleManga/devops/.github/workflows/deploy-docs.yml@main
    with:
      python-version: '3.x'
      requirements-file: 'requirements.txt'
      build-command: 'zensical build --clean'
      artifact-path: 'site'
      environment-name: 'github-pages'