name: Documentation

on:
  push:
    branches:
      - master
      - main

jobs:
  call-deploy:
    uses: TeleManga/devops/deployments/docs/deploy-docs.yml@main
    with:
      python-version: '3.x'
      requirements-file: 'requirements.txt'
      build-command: 'zensical build --clean'
      artifact-path: 'site'
      environment-name: 'github-pages'