name: PR Joke Review

on:
  pull_request:
    types: [opened, synchronize]
    
permissions:
      pull-requests: write

jobs:
  joke:
    uses: TeleManga/devops/.github/workflows/jokinator.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
